credentials:
  usernames:
    user:
      email: user@example.com
      name: User
      password: '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW' # 1234
cookie:
  expiry_days: 30
  key: 'random_signature_key'
  name: 'drugfood_guard_cookie'
preauthorized:
  emails: []
