credentials:
  usernames:
    user:
      email: user@example.com
      name: User
      password: '$2b$12$qbGyuPnyvDaP1D7quPK36.bYGSFNWkqZS9wZExFpE3/Kc/IhdIefG' # 1234
cookie:
  expiry_days: 30
  key: 'random_signature_key'
  name: 'drugfood_guard_cookie'
preauthorized:
  emails: []
